import os
import json
import re

import streamlit as st
from google import genai
from google.genai import types


# ============================================================
# 1. PAGE CONFIGURATION
# ============================================================

st.set_page_config(
    page_title="AI Fake News & Fact Checker",
    page_icon="📰",
    layout="wide"
)


# ============================================================
# 2. PAGE HEADER
# ============================================================

st.title("📰 Real-Time AI Fake News & Fact Checker")

st.caption(
    "AI-assisted fact checking using Gemini 2.5 Flash "
    "and Google Search Grounding."
)


# ============================================================
# 3. API CONFIGURATION
# ============================================================

api_key = (
    st.secrets.get("GOOGLE_API_KEY")
    or os.getenv("GOOGLE_API_KEY")
)

if not api_key:
    st.error(
        "⚠️ Google API key not found. "
        "Please configure GOOGLE_API_KEY in Streamlit "
        "secrets or as an environment variable."
    )
    st.stop()


client = genai.Client(api_key=api_key)


# ============================================================
# 4. INPUT VALIDATION
# ============================================================

def validate_input(news_text: str):

    news_text = news_text.strip()

    if not news_text:
        return False, "Please enter a news headline or claim."

    if len(news_text) < 10:
        return False, "Please provide a more complete claim."

    if len(news_text) > 5000:
        return False, "Please keep the input below 5000 characters."

    return True, ""


# ============================================================
# 5. JSON EXTRACTION
# ============================================================

def extract_json(text: str):
    """
    Extract JSON from Gemini's response.

    Gemini may occasionally wrap JSON inside markdown
    code fences even when explicitly instructed not to.
    """

    text = text.strip()

    # Remove markdown code fences
    text = re.sub(
        r"^```(?:json)?\s*",
        "",
        text,
        flags=re.IGNORECASE
    )

    text = re.sub(
        r"\s*```$",
        "",
        text
    )

    text = text.strip()

    # First attempt: entire response is JSON
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    # Second attempt: find JSON object inside response
    start = text.find("{")
    end = text.rfind("}")

    if start != -1 and end != -1 and end > start:

        json_text = text[start:end + 1]

        return json.loads(json_text)

    raise ValueError(
        "Could not find valid JSON in Gemini response."
    )


# ============================================================
# 6. EXTRACT REAL GOOGLE SEARCH SOURCES
# ============================================================

def extract_grounding_sources(response):
    """
    Extract actual web sources returned by Google Search
    Grounding.

    Sources come from Gemini grounding metadata rather than
    being generated by the model.
    """

    sources = []

    try:

        if not response.candidates:
            return sources

        candidate = response.candidates[0]

        grounding_metadata = (
            candidate.grounding_metadata
        )

        if not grounding_metadata:
            return sources

        grounding_chunks = (
            grounding_metadata.grounding_chunks
            or []
        )

        for chunk in grounding_chunks:

            web_source = getattr(
                chunk,
                "web",
                None
            )

            if not web_source:
                continue

            uri = getattr(
                web_source,
                "uri",
                None
            )

            title = getattr(
                web_source,
                "title",
                None
            )

            if uri:

                sources.append({
                    "title": title or "Web Source",
                    "url": uri
                })

    except Exception:
        return sources

    # --------------------------------------------------------
    # Remove duplicate URLs
    # --------------------------------------------------------

    unique_sources = []
    seen_urls = set()

    for source in sources:

        url = source["url"]

        if url not in seen_urls:

            seen_urls.add(url)

            unique_sources.append(source)

    return unique_sources


# ============================================================
# 7. GEMINI FACT-CHECKING ENGINE
# ============================================================

@st.cache_data(
    ttl=3600,
    show_spinner=False
)
def analyze_news_text(news_text: str):

    # --------------------------------------------------------
    # Google Search Grounding
    # --------------------------------------------------------

    config = types.GenerateContentConfig(
        tools=[
            types.Tool(
                google_search=types.GoogleSearch()
            )
        ]
    )


    # --------------------------------------------------------
    # Fact-checking prompt
    # --------------------------------------------------------

    prompt = f"""
You are an expert AI-assisted fact-checking system.

Your task is to verify the following news claim using
CURRENT information retrieved through Google Search.

IMPORTANT:

Do NOT simply decide whether the entire statement sounds true.

Instead:

1. Break the overall statement into individual factual claims.
2. Verify each factual claim independently.
3. Compare each claim against current web evidence.
4. Pay special attention to numbers, dates, names,
   locations, statistics and future events.
5. Do not treat a partially supported statement as completely
   REAL.
6. If evidence is insufficient, use UNVERIFIED.
7. Do not invent evidence.
8. Do not invent URLs.

============================================================
CLAIM STATUS
============================================================

SUPPORTED
Reliable evidence supports the claim.

CONTRADICTED
Reliable evidence directly contradicts the claim.

PARTIALLY_SUPPORTED
Some part of the claim is supported, but an important
detail is unsupported or inaccurate.

UNVERIFIED
There is insufficient reliable evidence.

============================================================
FINAL VERDICTS
============================================================

REAL
Important factual components are strongly supported.

MOSTLY REAL
Most important components are supported, with only minor
inaccuracies.

PARTIALLY TRUE
Some important components are true while other important
components are unsupported or inaccurate.

MISLEADING
The statement contains some factual basis but creates a
substantially incorrect impression.

MOSTLY FALSE
Most important components are unsupported or contradicted,
although a limited portion may be true.

FAKE
Reliable evidence strongly contradicts the main claim.

UNVERIFIED
There is insufficient reliable evidence to determine whether
the claim is true or false.

============================================================
CONFIDENCE
============================================================

Provide an AI-assigned confidence score from 0 to 100.

IMPORTANT:
This is NOT a statistically calibrated probability.

It represents the model's assessment of the strength and
consistency of the available evidence.

============================================================
OUTPUT FORMAT
============================================================

Return ONLY valid JSON.

Do NOT use markdown.

Do NOT use ```json.

Do NOT add any text before or after the JSON.

Use EXACTLY this structure:

{{
    "verdict": "UNVERIFIED",
    "confidence": 50,
    "summary": "Short explanation of the overall result.",
    "claim_analysis": [
        {{
            "claim": "Individual factual claim",
            "status": "UNVERIFIED",
            "explanation": "Explanation based on evidence."
        }}
    ],
    "evidence": [
        "Important evidence found during web search."
    ],
    "keywords": [
        "keyword1",
        "keyword2",
        "keyword3"
    ]
}}

Allowed verdict values:

REAL
MOSTLY REAL
PARTIALLY TRUE
MISLEADING
MOSTLY FALSE
FAKE
UNVERIFIED

Allowed claim status values:

SUPPORTED
CONTRADICTED
PARTIALLY_SUPPORTED
UNVERIFIED

============================================================
NEWS CLAIM
============================================================

{news_text}
"""


    # --------------------------------------------------------
    # Gemini API call
    # --------------------------------------------------------

    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt,
        config=config
    )


    # --------------------------------------------------------
    # Check response
    # --------------------------------------------------------

    if not response.text:

        raise ValueError(
            "Gemini returned an empty response."
        )


    # --------------------------------------------------------
    # Parse JSON
    # --------------------------------------------------------

    result = extract_json(
        response.text
    )


    # --------------------------------------------------------
    # Extract actual grounding sources
    # --------------------------------------------------------

    sources = extract_grounding_sources(
        response
    )

    result["sources"] = sources


    return result


# ============================================================
# 8. DISPLAY VERDICT
# ============================================================

def display_verdict(result):

    verdict = str(
        result.get(
            "verdict",
            "UNVERIFIED"
        )
    ).upper()

    try:

        confidence = float(
            result.get(
                "confidence",
                0
            )
        )

    except (ValueError, TypeError):

        confidence = 0


    summary = result.get(
        "summary",
        "No summary available."
    )

    claim_analysis = result.get(
        "claim_analysis",
        []
    )

    evidence = result.get(
        "evidence",
        []
    )

    keywords = result.get(
        "keywords",
        []
    )

    sources = result.get(
        "sources",
        []
    )


    # Keep confidence within 0-100
    confidence = max(
        0,
        min(100, confidence)
    )


    # ========================================================
    # OVERALL VERDICT
    # ========================================================

    st.markdown("## 🎯 Overall Verdict")


    if verdict == "REAL":

        st.success(
            f"✅ **{verdict}**"
        )

    elif verdict in (
        "MOSTLY REAL",
        "PARTIALLY TRUE"
    ):

        st.info(
            f"ℹ️ **{verdict}**"
        )

    elif verdict == "MISLEADING":

        st.warning(
            f"⚠️ **{verdict}**"
        )

    elif verdict in (
        "MOSTLY FALSE",
        "FAKE"
    ):

        st.error(
            f"🚨 **{verdict}**"
        )

    else:

        st.warning(
            f"❓ **{verdict}**"
        )


    # ========================================================
    # METRICS
    # ========================================================

    col1, col2, col3 = st.columns(3)

    with col1:

        st.metric(
            "AI Confidence",
            f"{confidence:.1f}%"
        )

    with col2:

        st.metric(
            "Claims Analyzed",
            len(claim_analysis)
        )

    with col3:

        st.metric(
            "Sources Found",
            len(sources)
        )


    st.caption(
        "AI Confidence represents the model's assessment "
        "of evidence strength. It is not a statistically "
        "calibrated probability."
    )


    # ========================================================
    # SUMMARY
    # ========================================================

    st.markdown("## 📋 Summary")

    st.write(summary)


    # ========================================================
    # CLAIM-BY-CLAIM ANALYSIS
    # ========================================================

    st.markdown(
        "## 🔍 Claim-by-Claim Analysis"
    )


    if claim_analysis:

        for index, item in enumerate(
            claim_analysis,
            start=1
        ):

            claim = item.get(
                "claim",
                "Unknown claim"
            )

            status = item.get(
                "status",
                "UNVERIFIED"
            )

            explanation = item.get(
                "explanation",
                "No explanation available."
            )


            # Status icon

            if status == "SUPPORTED":

                icon = "✅"

            elif status == "CONTRADICTED":

                icon = "❌"

            elif status == "PARTIALLY_SUPPORTED":

                icon = "⚠️"

            else:

                icon = "❓"


            with st.expander(
                f"{icon} Claim {index}: {status}"
            ):

                st.markdown(
                    f"**Claim:** {claim}"
                )

                st.markdown(
                    f"**Status:** `{status}`"
                )

                st.write(
                    explanation
                )

    else:

        st.info(
            "No individual claims were returned."
        )


    # ========================================================
    # EVIDENCE
    # ========================================================

    st.markdown("## 📚 Evidence")


    if evidence:

        for index, item in enumerate(
            evidence,
            start=1
        ):

            st.markdown(
                f"**{index}.** {item}"
            )

    else:

        st.info(
            "No evidence was returned."
        )


    # ========================================================
    # REAL WEB SOURCES
    # ========================================================

    st.markdown("## 🔗 Sources")


    if sources:

        for index, source in enumerate(
            sources,
            start=1
        ):

            title = source.get(
                "title",
                "Web Source"
            )

            url = source.get(
                "url"
            )

            if url:

                st.markdown(
                    f"{index}. [{title}]({url})"
                )

    else:

        st.info(
            "No grounding sources were returned."
        )


    # ========================================================
    # KEYWORDS
    # ========================================================

    st.markdown("## 🏷️ Keywords")


    if keywords:

        st.write(
            " • ".join(
                str(keyword)
                for keyword in keywords
            )
        )

    else:

        st.write(
            "No keywords available."
        )


# ============================================================
# 9. MAIN INPUT
# ============================================================

st.subheader(
    "Paste the News Article or Claim Below 👇"
)


text_input = st.text_area(
    "News Text:",
    height=200,
    max_chars=5000,
    placeholder=(
        "Paste a headline or news claim here..."
    )
)


st.caption(
    f"{len(text_input)}/5000 characters"
)


# ============================================================
# 10. CHECK CREDIBILITY BUTTON
# ============================================================

if st.button(
    "🔍 Check Credibility",
    type="primary",
    use_container_width=True
):

    is_valid, error_message = validate_input(
        text_input
    )


    if not is_valid:

        st.warning(
            error_message
        )

    else:

        with st.spinner(
            "🔎 Searching current web sources and "
            "verifying individual claims..."
        ):

            try:

                result = analyze_news_text(
                    text_input.strip()
                )


                # Store result in session state

                st.session_state[
                    "last_result"
                ] = result


            except json.JSONDecodeError:

                st.error(
                    "❌ Gemini returned a response that "
                    "could not be parsed as JSON."
                )

                st.info(
                    "Try submitting the claim again."
                )


            except ValueError as e:

                st.error(
                    f"❌ {str(e)}"
                )


            except Exception as e:

                st.error(
                    "❌ Fact-checking failed."
                )

                st.caption(
                    f"Technical details: {str(e)}"
                )


# ============================================================
# 11. DISPLAY LAST RESULT
# ============================================================

if "last_result" in st.session_state:

    st.divider()

    display_verdict(
        st.session_state[
            "last_result"
        ]
    )


# ============================================================
# 12. DISCLAIMER
# ============================================================

st.divider()

st.caption(
    "⚠️ Disclaimer: This application provides an "
    "AI-assisted credibility assessment and should not "
    "be treated as an absolute determination of truth. "
    "Verify important claims using multiple authoritative "
    "sources."
)